### ISSUE TITLE
Add configurable periodic messages

### ISSUE THREAD

**Issue by vcarl** [reactiflux/reactibot#13]
It would be great to be able to have Reactibot post messages to several channels every so often. A daily post in #jobs reminding people of the rules would be great, and a welcome post to #introductions pointing people to the guidelines and tips. 

We can iron out exact messages later, being able to set up what channel, how often, and the message would be great.

**Comment by nickmccurdy** [comment]
I think our reworked guidelines page and other parts of the site and Discord channel descriptions would be a better place for this information. That way it's easier to consistently find it as well.

**Comment by vcarl** [comment]
The website + channel descriptions server different purposes from this. Many, many different regulars have remarked to me that they weren't aware of information on the site/in descriptions, elevating it to the channel means that it's occasionally the topic of discussion, not just available for anyone who looks for it

**Comment by rosofo** [comment]
The PR I linked above has been merged and closes this ^
