### ISSUE TITLE
Automatically create threads for specified channels

### ISSUE THREAD

**Issue by vcarl** [reactiflux/reactibot#134]
For specified channels:

* every message has a thread created for it, named something readable (name + date stamp?)
* replies are removed and the sender Dm'd instructions
* a !close command only the author can use (or maybe mvps and maybe a "helper" type role with this ability as well)
  * this is maybe not helpful, cuz afaik members can always close their own threads
* reactibot closes after 6 hours, and sends a message with instructions on following up
* instructions link to parent message and suggest replying to it if it's relevant

**Comment by Padmanabh82** [comment]
I have more suggestions like, bot will pin the threads that are active or not being answered and thread's name should include timestamp, name of author, whole error or question (like why this unexpected behaviour is occurring)

**Comment by vcarl** [comment]
Instead of a !close command, I think instead a ✅ reaction that will mark an answer as "accepted" and close the thread immediately is more helpful

**Comment by nickmccurdy** [comment]
I believe we can also use buttons for this since we've upgraded the API.
