### ISSUE TITLE
Thread channels are double-sending "this has an answer" messages

### ISSUE THREAD

**Issue by vcarl** [reactiflux/reactibot#173]
The code to trigger a "this has an answer" bot response will fire every time someone else reacts, unintentionally sending multiple messages. We should be able to check who the current reaction is from, instead of whether the author has reacted, or we could read thread messages to see if the bot has already responded, or we could track a list of threads that have been "resolved".

**Comment by definoob** [comment]
I don't know how this actually works as I've never played in threads but would like to pick this up. 
Thanks.

**Comment by vcarl** [comment]
Cool, sounds good! Let me know if you want to pair or talk through the problem

**Comment by vcarl** [comment]
closed by #347
