### ISSUE TITLE
!lock and !unlock changes

### ISSUE THREAD

**Issue by Padmanabh82** [reactiflux/reactibot#185]
I think !lock should be renamed to ! archive and !unlock should be to !unarchive, as it is more used words and appropriate for use of !lock and ! unlock

**Comment by nickmccurdy** [comment]
I disagree personally. Archiving implies that we're either permanently archiving a channel by moving it to the Archived category, or archiving a thread. However, we may want to just temporarily lock a channel or thread with a heated discussion, without permanently archiving it.

**Comment by Padmanabh82** [comment]
Ok, np (i will wait for others opinion and then close it)
