### ISSUE TITLE
Improve anti-scam

### ISSUE THREAD

**Issue by Padmanabh82** [reactiflux/reactibot#187]
Aa, so.. i am here with a new issue for improving our scam/spam dection system. Here is a famous tech YouTuber named [ThioJoe](https://youtube.com/c/ThioJoe) has made a small [program](https://github.com/ThioJoe/YT-Spammer-Purge) in python in his vedios [part1](https://youtu.be/-vOakOgYLUI) [part2](https://youtu.be/2tRppXW_aKo) for removing spams and scam in yt's  comments. So, i think we can or should implement his anti-scam system in js in our bot. Now i am waiting for staff's opinions

**Comment by vcarl** [comment]
Dupe of #117

**Comment by Padmanabh82** [comment]
@vcarl is it same ??? Did you checked code ???
