### ISSUE TITLE
Block crypto posters from job board for a time after suggesting

### ISSUE THREAD

**Issue by vcarl** [reactiflux/reactibot#257]
We have a lot of crypto posters who have been updating their post until they find a way around the filter, which isn't the point. By blocking them from re-posting for an extended period of time, we'd more effectively discourage these low-value posters from returning.

We could do this in-memory, just storing their user IDs for a period of time and preventing them from posting. We might want to continue to reply with the referral link, maybe escalating to a timeout if they keep posting

**Comment by nickmccurdy** [comment]
Could we time them out instead?

**Comment by vcarl** [comment]
Yeah it probably makes sense to time them out if they keep posting but I don't think it needs to happen immediately
