### ISSUE TITLE
create a command for react keys

### ISSUE THREAD

**Issue by CaptainTux** [reactiflux/reactibot#262]
the topic seems to come up quite frequently, either explicitly or implicitly
I think it would be useful to have a `!keys` command for such situations.
for example today I saw someone using UUIDs as keys which got generated on every render, and it wasn't the first time
perhaps something like (I'm bad with coming up with educational messages, forgive me, there should probably be another sentence or 2)

> Keys are important if you map over an array and the callback returns JSX
> *some more here*
> For further information see
> - https://beta.reactjs.org/learn/rendering-lists#keeping-list-items-in-order-with-key
> - https://kentcdodds.com/blog/understanding-reacts-key-prop

**Comment by louis-young** [comment]
I think this is a great suggestion. Thanks for suggesting it and raising an issue @CaptainTux. 

I've tweaked the blurb slightly and raised https://github.com/reactiflux/reactibot/pull/263.
