### ISSUE TITLE
Add daily/weekly/monthly scheduled post of top N posts from /r/reactjs

### ISSUE THREAD

**Issue by vcarl** [reactiflux/reactibot#350]
I think it'd be great to figure out how to more strongly relate these communities, pull in a stream of links and other shared materials from the subreddit into the Discord. I've had the thought of some kind of archive of point-in-time top links, think this might be a good way to do so

**Comment by DanielFGray** [comment]
We can scrape from Reddit API pretty easily:  
https://www.reddit.com/r/reactjs/top.json?sort=top&t=week

**Comment by vcarl** [comment]
This would probably be pretty easy to add with our existing [`scheduleTask` helper](https://github.com/reactiflux/reactibot/blob/main/src/helpers/schedule.ts#L47) 

See examples of usage:
https://github.com/reactiflux/reactibot/blob/5f727b054b594547071383c2aff363f160afec50/src/features/scheduled-messages.ts#L159
https://github.com/reactiflux/reactibot/blob/5f727b054b594547071383c2aff363f160afec50/src/features/jobs-moderation.ts#L88

**Comment by vcarl** [comment]
Here's a thought: RSS feeds for all the React/React Native newsletters + reddit + HN, post based on some threshold combination of score, # of sources it's been posted to, etc. Feels like we could get a very high-signal channel of resources that's auto-generated based on that style of curation

**Comment by vcarl** [comment]
This is ~ the product swyx is building https://www.youtube.com/watch?v=9VcTbBce_eU

**Comment by vcarl** [comment]
Resolved in #397, removed in #408 and moved to [reactiflux/feeds](https://github.com/reactiflux/feeds)
