### ISSUE TITLE
Consider using Sapphire framework

### ISSUE THREAD

**Issue by nickmccurdy** [reactiflux/reactibot#46]
- [Gears](https://gears.enitoni.dev/) [[example](https://gitlab.com/enitoni/nodeiflux-bot)]
- [Commando](https://discord.js.org/#/docs/commando/master/general/welcome)

**Comment by nickmccurdy** [comment]
Alternatively we could use [slash commands](https://discord.com/developers/docs/interactions/slash-commands) which seem to have a much better UX

**Comment by nickmccurdy** [comment]
Gears and Commando both seem to not support Discord.js 13, and I don't think it's worth the effort switching to another library when Discord.js already has thread support, so I'll close this for now.

**Comment by nickmccurdy** [comment]
Commando has been archived on GitHub, so I assume it's no longer supported.

**Comment by nickmccurdy** [comment]
discord.js is now recommending Sapphire instead of Commando. It seems to already support threads and provide helpers for command management, so it may be worth looking into at some point, especially if #131 doesn't end up making it easier to maintain our commands.

**Comment by Padmanabh82** [comment]
@nickmccurdy do we need this ??? If not please close this

**Comment by nickmccurdy** [comment]
I'd still like to look into this more, it's just not a priority right now

**Comment by vcarl** [comment]
I'm going to close this as it's 3 years old
