### ISSUE TITLE
Auto restart

### ISSUE THREAD

**Issue by nickmccurdy** [reactiflux/reactibot#50]
It's possible to have Docker automatically restart the server when it crashes using `--restart=on-failure:10`, which would help our uptime when errors aren't handled

**Comment by dylangarcia** [comment]
I don't think this is necessary anymore since I added global exception and unhandled promise rejection handlers.

**Comment by nickmccurdy** [comment]
This seems to be an issue still.

**Comment by vcarl** [comment]
Believe this is resolved now that it runs on k8s, I haven't observed an outage in a good while
